#!/usr/bin/env node
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SKILLS_DIR = join(__dirname, "..", "convex", "systemSkills");
const OUTPUT = join(SKILLS_DIR, "_registry.generated.ts");

function parseFrontmatter(raw) {
  const normalized = raw.replace(/\r\n/g, "\n");
  const match = normalized.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!match) return { meta: {}, body: normalized.trim() };
  const meta = {};
  for (const line of match[1].split("\n")) {
    const idx = line.indexOf(":");
    if (idx > 0) meta[line.slice(0, idx).trim()] = line.slice(idx + 1).trim();
  }
  return { meta, body: match[2].trim() };
}

const entries = [];
for (const slug of readdirSync(SKILLS_DIR).sort()) {
  const dir = join(SKILLS_DIR, slug);
  if (!statSync(dir).isDirectory()) continue;
  const skillPath = join(dir, "SKILL.md");
  let raw;
  try {
    raw = readFileSync(skillPath, "utf8");
  } catch {
    continue;
  }
  const { meta, body } = parseFrontmatter(raw);
  if (!meta.name || !meta.description) {
    throw new Error(
      `[generateSystemSkillsRegistry] ${skillPath} is missing 'name' or 'description' in frontmatter.`,
    );
  }
  entries.push({ name: meta.name, description: meta.description, content: body });
}

const lines = [
  "// AUTO-GENERATED by scripts/generateSystemSkillsRegistry.mjs — do not edit.",
  "// Source: convex/systemSkills/<slug>/SKILL.md",
  "",
  "export type SystemSkill = {",
  "  name: string;",
  "  description: string;",
  "  content: string;",
  "};",
  "",
  "export const SYSTEM_SKILLS: readonly SystemSkill[] = [",
];
for (const e of entries) {
  lines.push("  {");
  lines.push(`    name: ${JSON.stringify(e.name)},`);
  lines.push(`    description: ${JSON.stringify(e.description)},`);
  lines.push(`    content: ${JSON.stringify(e.content)},`);
  lines.push("  },");
}
lines.push("] as const;");
lines.push("");
lines.push("export function findSystemSkillByName(name: string): SystemSkill | null {");
lines.push("  return SYSTEM_SKILLS.find((s) => s.name === name) ?? null;");
lines.push("}");
lines.push("");

writeFileSync(OUTPUT, lines.join("\n"), "utf8");
console.log(
  `[generateSystemSkillsRegistry] wrote ${entries.length} skill(s) to ${OUTPUT}`,
);
