#!/usr/bin/env node
import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SKILLS_DIR = join(__dirname, "..", "convex", "systemSkills");
const OUTPUT = join(SKILLS_DIR, "_registry.generated.ts");

function parseFrontmatter(raw) {
  const normalized = raw.replace(/\r\n/g, "\n");
  const match = normalized.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!match) return { meta: {}, body: normalized.trim() };
  const meta = {};
  for (const line of match[1].split("\n")) {
    const idx = line.indexOf(":");
    if (idx > 0) meta[line.slice(0, idx).trim()] = line.slice(idx + 1).trim();
  }
  return { meta, body: match[2].trim() };
}

const entries = [];
for (const slug of readdirSync(SKILLS_DIR).sort()) {
  const dir = join(SKILLS_DIR, slug);
  if (!statSync(dir).isDirectory()) continue;
  const skillPath = join(dir, "SKILL.md");
  let raw;
  try {
    raw = readFileSync(skillPath, "utf8");
  } catch {
    continue;
  }
  const { meta, body } = parseFrontmatter(raw);
  if (!meta.name || !meta.description) {
    throw new Error(
      `[generateSystemSkillsRegistry] ${skillPath} is missing 'name' or 'description' in frontmatter.`,
    );
  }
  entries.push({
    name: meta.name,
    description: meta.description,
    content: body,
    // `hidden: true` : le skill reste chargeable par son nom exact (load_skill)
    // mais n'est pas listé dans <available_skills>. Sert aux sous-sections
    // qu'un skill d'entrée énumère lui-même (cf. `nolenor-user-manual`).
    hidden: meta.hidden === "true",
  });
}

const seenNames = new Set();
for (const e of entries) {
  if (seenNames.has(e.name)) {
    throw new Error(
      `[generateSystemSkillsRegistry] duplicate skill name '${e.name}'.`,
    );
  }
  seenNames.add(e.name);
}

// Une référence à un skill masqué qui ne correspond à aucun skill (faute de
// frappe dans un renvoi) est une impasse pour Nolë : on la refuse au build.
// Seuls les noms de la famille d'un skill masqué (même premier segment, par
// exemple `manual-…`) sont contrôlés, pour ne pas prendre n'importe quel mot en
// code inline pour un renvoi.
const hiddenFamilies = new Set(
  entries.filter((e) => e.hidden).map((e) => e.name.split("-")[0]),
);
for (const e of entries) {
  for (const match of e.content.matchAll(/`([a-z0-9]+(?:-[a-z0-9]+)+)`/g)) {
    const token = match[1];
    if (hiddenFamilies.has(token.split("-")[0]) && !seenNames.has(token)) {
      throw new Error(
        `[generateSystemSkillsRegistry] '${e.name}' refers to unknown skill '${token}'.`,
      );
    }
  }
}

// Un skill masqué n'est joignable que si un skill listé le nomme : sans cela,
// il serait chargeable en théorie mais introuvable en pratique.
const listedEntries = entries.filter((e) => !e.hidden);
for (const e of entries.filter((entry) => entry.hidden)) {
  if (!listedEntries.some((listed) => listed.content.includes(e.name))) {
    throw new Error(
      `[generateSystemSkillsRegistry] hidden skill '${e.name}' is not referenced by any listed skill, so nobody can reach it.`,
    );
  }
}

const lines = [
  "// AUTO-GENERATED by scripts/generateSystemSkillsRegistry.mjs — do not edit.",
  "// Source: convex/systemSkills/<slug>/SKILL.md",
  "",
  "export type SystemSkill = {",
  "  name: string;",
  "  description: string;",
  "  content: string;",
  "  /** Chargeable par nom, mais absent de <available_skills>. */",
  "  hidden?: boolean;",
  "};",
  "",
  "export const SYSTEM_SKILLS: readonly SystemSkill[] = [",
];
for (const e of entries) {
  lines.push("  {");
  lines.push(`    name: ${JSON.stringify(e.name)},`);
  lines.push(`    description: ${JSON.stringify(e.description)},`);
  lines.push(`    content: ${JSON.stringify(e.content)},`);
  if (e.hidden) lines.push("    hidden: true,");
  lines.push("  },");
}
lines.push("] as const;");
lines.push("");
lines.push("export function findSystemSkillByName(name: string): SystemSkill | null {");
lines.push("  return SYSTEM_SKILLS.find((s) => s.name === name) ?? null;");
lines.push("}");
lines.push("");

writeFileSync(OUTPUT, lines.join("\n"), "utf8");
console.log(
  `[generateSystemSkillsRegistry] wrote ${entries.length} skill(s) to ${OUTPUT}`,
);
