/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SettingsTemplatesRouteImport } from './routes/settings/templates'
import { Route as SettingsSkillsRouteImport } from './routes/settings/skills'
import { Route as SettingsExportRouteImport } from './routes/settings/export'
import { Route as SettingsApiTokensRouteImport } from './routes/settings/api-tokens'
import { Route as SettingsAiUsageRouteImport } from './routes/settings/ai-usage'
import { Route as SettingsAccountRouteImport } from './routes/settings/account'
import { Route as CanvasCanvasIdRouteImport } from './routes/canvas/$canvasId'
import { Route as SettingsRecipesIndexRouteImport } from './routes/settings/recipes/index'
import { Route as SettingsRecipesEditRecipeIdRouteImport } from './routes/settings/recipes/edit.$recipeId'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsTemplatesRoute = SettingsTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsSkillsRoute = SettingsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsExportRoute = SettingsExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsApiTokensRoute = SettingsApiTokensRouteImport.update({
  id: '/api-tokens',
  path: '/api-tokens',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAiUsageRoute = SettingsAiUsageRouteImport.update({
  id: '/ai-usage',
  path: '/ai-usage',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const CanvasCanvasIdRoute = CanvasCanvasIdRouteImport.update({
  id: '/canvas/$canvasId',
  path: '/canvas/$canvasId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRecipesIndexRoute = SettingsRecipesIndexRouteImport.update({
  id: '/recipes/',
  path: '/recipes/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsRecipesEditRecipeIdRoute =
  SettingsRecipesEditRecipeIdRouteImport.update({
    id: '/recipes/edit/$recipeId',
    path: '/recipes/edit/$recipeId',
    getParentRoute: () => SettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/signin': typeof SigninRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/ai-usage': typeof SettingsAiUsageRoute
  '/settings/api-tokens': typeof SettingsApiTokensRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/recipes': typeof SettingsRecipesIndexRoute
  '/settings/recipes/edit/$recipeId': typeof SettingsRecipesEditRecipeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/ai-usage': typeof SettingsAiUsageRoute
  '/settings/api-tokens': typeof SettingsApiTokensRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/settings': typeof SettingsIndexRoute
  '/settings/recipes': typeof SettingsRecipesIndexRoute
  '/settings/recipes/edit/$recipeId': typeof SettingsRecipesEditRecipeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/signin': typeof SigninRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/ai-usage': typeof SettingsAiUsageRoute
  '/settings/api-tokens': typeof SettingsApiTokensRoute
  '/settings/export': typeof SettingsExportRoute
  '/settings/skills': typeof SettingsSkillsRoute
  '/settings/templates': typeof SettingsTemplatesRoute
  '/settings/': typeof SettingsIndexRoute
  '/settings/recipes/': typeof SettingsRecipesIndexRoute
  '/settings/recipes/edit/$recipeId': typeof SettingsRecipesEditRecipeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/signin'
    | '/canvas/$canvasId'
    | '/settings/account'
    | '/settings/ai-usage'
    | '/settings/api-tokens'
    | '/settings/export'
    | '/settings/skills'
    | '/settings/templates'
    | '/settings/'
    | '/settings/recipes'
    | '/settings/recipes/edit/$recipeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/canvas/$canvasId'
    | '/settings/account'
    | '/settings/ai-usage'
    | '/settings/api-tokens'
    | '/settings/export'
    | '/settings/skills'
    | '/settings/templates'
    | '/settings'
    | '/settings/recipes'
    | '/settings/recipes/edit/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/signin'
    | '/canvas/$canvasId'
    | '/settings/account'
    | '/settings/ai-usage'
    | '/settings/api-tokens'
    | '/settings/export'
    | '/settings/skills'
    | '/settings/templates'
    | '/settings/'
    | '/settings/recipes/'
    | '/settings/recipes/edit/$recipeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  SigninRoute: typeof SigninRoute
  CanvasCanvasIdRoute: typeof CanvasCanvasIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/templates': {
      id: '/settings/templates'
      path: '/templates'
      fullPath: '/settings/templates'
      preLoaderRoute: typeof SettingsTemplatesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/skills': {
      id: '/settings/skills'
      path: '/skills'
      fullPath: '/settings/skills'
      preLoaderRoute: typeof SettingsSkillsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/export': {
      id: '/settings/export'
      path: '/export'
      fullPath: '/settings/export'
      preLoaderRoute: typeof SettingsExportRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/api-tokens': {
      id: '/settings/api-tokens'
      path: '/api-tokens'
      fullPath: '/settings/api-tokens'
      preLoaderRoute: typeof SettingsApiTokensRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/ai-usage': {
      id: '/settings/ai-usage'
      path: '/ai-usage'
      fullPath: '/settings/ai-usage'
      preLoaderRoute: typeof SettingsAiUsageRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/canvas/$canvasId': {
      id: '/canvas/$canvasId'
      path: '/canvas/$canvasId'
      fullPath: '/canvas/$canvasId'
      preLoaderRoute: typeof CanvasCanvasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/recipes/': {
      id: '/settings/recipes/'
      path: '/recipes'
      fullPath: '/settings/recipes'
      preLoaderRoute: typeof SettingsRecipesIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/recipes/edit/$recipeId': {
      id: '/settings/recipes/edit/$recipeId'
      path: '/recipes/edit/$recipeId'
      fullPath: '/settings/recipes/edit/$recipeId'
      preLoaderRoute: typeof SettingsRecipesEditRecipeIdRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsAiUsageRoute: typeof SettingsAiUsageRoute
  SettingsApiTokensRoute: typeof SettingsApiTokensRoute
  SettingsExportRoute: typeof SettingsExportRoute
  SettingsSkillsRoute: typeof SettingsSkillsRoute
  SettingsTemplatesRoute: typeof SettingsTemplatesRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SettingsRecipesIndexRoute: typeof SettingsRecipesIndexRoute
  SettingsRecipesEditRecipeIdRoute: typeof SettingsRecipesEditRecipeIdRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsAiUsageRoute: SettingsAiUsageRoute,
  SettingsApiTokensRoute: SettingsApiTokensRoute,
  SettingsExportRoute: SettingsExportRoute,
  SettingsSkillsRoute: SettingsSkillsRoute,
  SettingsTemplatesRoute: SettingsTemplatesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SettingsRecipesIndexRoute: SettingsRecipesIndexRoute,
  SettingsRecipesEditRecipeIdRoute: SettingsRecipesEditRecipeIdRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  SigninRoute: SigninRoute,
  CanvasCanvasIdRoute: CanvasCanvasIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
