/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsSkillsRouteImport } from './routes/settings/skills'
import { Route as SettingsRecipesRouteImport } from './routes/settings/recipes'
import { Route as CanvasCanvasIdRouteImport } from './routes/canvas/$canvasId'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSkillsRoute = SettingsSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsRecipesRoute = SettingsRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const CanvasCanvasIdRoute = CanvasCanvasIdRouteImport.update({
  id: '/canvas/$canvasId',
  path: '/canvas/$canvasId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/signin': typeof SigninRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/settings/recipes': typeof SettingsRecipesRoute
  '/settings/skills': typeof SettingsSkillsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/signin': typeof SigninRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/settings/recipes': typeof SettingsRecipesRoute
  '/settings/skills': typeof SettingsSkillsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/signin': typeof SigninRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/settings/recipes': typeof SettingsRecipesRoute
  '/settings/skills': typeof SettingsSkillsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/signin'
    | '/canvas/$canvasId'
    | '/settings/recipes'
    | '/settings/skills'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/signin'
    | '/canvas/$canvasId'
    | '/settings/recipes'
    | '/settings/skills'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/signin'
    | '/canvas/$canvasId'
    | '/settings/recipes'
    | '/settings/skills'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  SigninRoute: typeof SigninRoute
  CanvasCanvasIdRoute: typeof CanvasCanvasIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/skills': {
      id: '/settings/skills'
      path: '/skills'
      fullPath: '/settings/skills'
      preLoaderRoute: typeof SettingsSkillsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/recipes': {
      id: '/settings/recipes'
      path: '/recipes'
      fullPath: '/settings/recipes'
      preLoaderRoute: typeof SettingsRecipesRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/canvas/$canvasId': {
      id: '/canvas/$canvasId'
      path: '/canvas/$canvasId'
      fullPath: '/canvas/$canvasId'
      preLoaderRoute: typeof CanvasCanvasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsRecipesRoute: typeof SettingsRecipesRoute
  SettingsSkillsRoute: typeof SettingsSkillsRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsRecipesRoute: SettingsRecipesRoute,
  SettingsSkillsRoute: SettingsSkillsRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  SigninRoute: SigninRoute,
  CanvasCanvasIdRoute: CanvasCanvasIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
