const colors = {
  blue: {
    label: "Blue",
    nodeBg: "bg-[var(--tag-blue-soft)]",
    lightBg: "bg-[var(--tag-blue-soft)]/60",
    nodeBorder: "border-[var(--tag-blue-border)]",
    accentBg: "bg-[var(--tag-blue-solid)]",
    textColor: "text-[var(--tag-blue-text)]",
  },
  red: {
    label: "Red",
    nodeBg: "bg-[var(--tag-red-soft)]",
    lightBg: "bg-[var(--tag-red-soft)]/60",
    accentBg: "bg-[var(--tag-red-solid)]",
    nodeBorder: "border-[var(--tag-red-border)]",
    textColor: "text-[var(--tag-red-text)]",
  },
  yellow: {
    label: "Yellow",
    nodeBg: "bg-[var(--tag-yellow-soft)]",
    lightBg: "bg-[var(--tag-yellow-soft)]/60",
    accentBg: "bg-[var(--tag-yellow-solid)]",
    nodeBorder: "border-[var(--tag-yellow-border)]",
    textColor: "text-[var(--tag-yellow-text)]",
  },
  green: {
    label: "Green",
    nodeBg: "bg-[var(--tag-green-soft)]",
    lightBg: "bg-[var(--tag-green-soft)]/60",
    nodeBorder: "border-[var(--tag-green-border)]",
    accentBg: "bg-[var(--tag-green-solid)]",
    textColor: "text-[var(--tag-green-text)]",
  },
  pink: {
    label: "Pink",
    nodeBg: "bg-[var(--tag-pink-soft)]",
    lightBg: "bg-[var(--tag-pink-soft)]/60",
    nodeBorder: "border-[var(--tag-pink-border)]",
    accentBg: "bg-[var(--tag-pink-solid)]",
    textColor: "text-[var(--tag-pink-text)]",
  },
  orange: {
    label: "Orange",
    nodeBg: "bg-[var(--tag-orange-soft)]",
    lightBg: "bg-[var(--tag-orange-soft)]/60",
    nodeBorder: "border-[var(--tag-orange-border)]",
    accentBg: "bg-[var(--tag-orange-solid)]",
    textColor: "text-[var(--tag-orange-text)]",
  },
  purple: {
    label: "Purple",
    nodeBg: "bg-[var(--tag-purple-soft)]",
    lightBg: "bg-[var(--tag-purple-soft)]/60",
    nodeBorder: "border-[var(--tag-purple-border)]",
    accentBg: "bg-[var(--tag-purple-solid)]",
    textColor: "text-[var(--tag-purple-text)]",
  },
  default: {
    label: "Default",
    nodeBg: "bg-card",
    lightBg: "bg-muted",
    nodeBorder: "border-border",
    accentBg: "bg-[var(--tag-slate-solid)]",
    textColor: "text-muted-foreground",
  },
  transparent: {
    label: "Transparent",
    nodeBg: "bg-transparent",
    lightBg: "bg-transparent",
    nodeBorder: "border-transparent",
    textColor: "text-muted-foreground",
    accentBg: "bg-transparent",
  },
} as const;

export { colors };
